import Link from "next/link";
import { ArrowLeft, FileText, Users, Shield, AlertTriangle, Scale } from "lucide-react";
import { Button } from "@/components/ui/Button";
import FadeIn from "@/components/animations/FadeIn";

export default function TermsOfServicePage() {
  const sections = [
    {
      icon: <FileText className="w-6 h-6" />,
      title: "Acceptance of Terms",
      content: [
        {
          subtitle: "Agreement to Terms",
          text: "By accessing and using AQLAAN's services, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service."
        },
        {
          subtitle: "Changes to Terms",
          text: "We reserve the right to modify these terms at any time. We will notify users of any material changes via email or platform notification."
        }
      ]
    },
    {
      icon: <Users className="w-6 h-6" />,
      title: "User Accounts",
      content: [
        {
          subtitle: "Account Creation",
          text: "To access certain features of our platform, you must create an account. You are responsible for maintaining the confidentiality of your account credentials."
        },
        {
          subtitle: "Account Responsibilities",
          text: "You are responsible for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account."
        },
        {
          subtitle: "Account Termination",
          text: "We reserve the right to terminate or suspend your account at our discretion, with or without cause."
        }
      ]
    },
    {
      icon: <Shield className="w-6 h-6" />,
      title: "Use of Services",
      content: [
        {
          subtitle: "Permitted Use",
          text: "You may use our services only for lawful purposes and in accordance with these terms. You agree not to use our services in any way that violates applicable laws or regulations."
        },
        {
          subtitle: "Prohibited Activities",
          text: "You may not use our services to transmit harmful code, infringe intellectual property rights, or engage in any fraudulent or illegal activities."
        },
        {
          subtitle: "Service Availability",
          text: "While we strive for high availability, we do not guarantee uninterrupted access to our services. We may perform maintenance that temporarily limits access."
        }
      ]
    },
    {
      icon: <AlertTriangle className="w-6 h-6" />,
      title: "Intellectual Property",
      content: [
        {
          subtitle: "Our Content",
          text: "All content, features, and functionality of our platform are owned by AQLAAN and are protected by copyright, trademark, and other intellectual property laws."
        },
        {
          subtitle: "Your Content",
          text: "You retain ownership of content you submit to our platform. By submitting content, you grant us a license to use, modify, and display that content as necessary to provide our services."
        },
        {
          subtitle: "AI-Generated Content",
          text: "Content generated by our AI systems may be subject to different licensing terms. Please review our specific guidelines for AI-generated content."
        }
      ]
    },
    {
      icon: <Scale className="w-6 h-6" />,
      title: "Limitation of Liability",
      content: [
        {
          subtitle: "Service Disclaimers",
          text: "Our services are provided 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of AI-generated content."
        },
        {
          subtitle: "Liability Limits",
          text: "In no event shall AQLAAN be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of our services."
        },
        {
          subtitle: "Indemnification",
          text: "You agree to indemnify and hold harmless AQLAAN from any claims, damages, or expenses arising from your use of our services or violation of these terms."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <section className="relative pt-32 pb-20 overflow-hidden">
        <div className="absolute inset-0 bg-black/20" />
        <div className="absolute inset-0 bg-linear-to-r from-blue-600/10 to-cyan-600/10" />

        <div className="relative max-w-4xl mx-auto px-6">
          <FadeIn>
            <div className="text-center mb-8">
              <Link href="/" className="inline-flex items-center text-gray-400 hover:text-white transition-colors mb-8">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Link>

              <h1 className="text-4xl md:text-6xl font-bold mb-6">
                Terms of
                <span className="bg-linear-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                  {" "}Service
                </span>
              </h1>
              <p className="text-xl text-gray-300 max-w-3xl mx-auto">
                Please read these terms carefully before using our AI platform and services.
              </p>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* Content */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-6">
          <div className="space-y-16">
            {sections.map((section, index) => (
              <FadeIn key={index} delay={index * 0.1}>
                <div className="border-b border-gray-800 pb-12 last:border-b-0">
                  <div className="flex items-center mb-6">
                    <div className="w-12 h-12 bg-linear-to-r from-blue-600 to-cyan-500 rounded-lg flex items-center justify-center mr-4 text-white">
                      {section.icon}
                    </div>
                    <h2 className="text-2xl font-bold text-white">{section.title}</h2>
                  </div>

                  <div className="space-y-6 ml-16">
                    {section.content.map((item, itemIndex) => (
                      <div key={itemIndex}>
                        <h3 className="text-lg font-semibold text-blue-400 mb-2">
                          {item.subtitle}
                        </h3>
                        <p className="text-gray-300 leading-relaxed">
                          {item.text}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </FadeIn>
            ))}
          </div>

          {/* Contact Information */}
          <FadeIn delay={0.6}>
            <div className="mt-16 p-8 bg-gray-900/50 border border-gray-800 rounded-lg">
              <h3 className="text-xl font-bold text-white mb-4">Questions About These Terms?</h3>
              <p className="text-gray-300 mb-6">
                If you have any questions about these Terms of Service, please contact us:
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link href="/contact">
                  <Button className="bg-linear-to-r from-blue-600 to-cyan-500 hover:from-blue-700 hover:to-cyan-600 text-white font-semibold px-6 py-3">
                    Contact Us
                  </Button>
                </Link>
                <a href="mailto:legal@aqlaan.com">
                  <Button variant="outline" className="border-gray-600 text-gray-300 hover:text-white px-6 py-3">
                    legal@aqlaan.com
                  </Button>
                </a>
              </div>
            </div>
          </FadeIn>

          {/* Last Updated */}
          <div className="mt-16 pt-8 border-t border-gray-800">
            <p className="text-gray-400 text-sm text-center">
              Last updated: October 23, 2025
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}